# Generated by Django 4.1.4 on 2022-12-30 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cosmetics',
            new_name='Shoes',
        ),
        migrations.RenameModel(
            old_name='HairGrooming',
            new_name='Watches',
        ),
    ]
