# Generated by Django 4.1.4 on 2023-01-01 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_rename_electronics_books'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shoes',
            new_name='Book',
        ),
        migrations.RenameModel(
            old_name='Phones',
            new_name='Clothe',
        ),
        migrations.RenameModel(
            old_name='Laptops',
            new_name='Laptop',
        ),
        migrations.RenameModel(
            old_name='Watches',
            new_name='Phone',
        ),
        migrations.RenameModel(
            old_name='Clothes',
            new_name='Shoe',
        ),
        migrations.RenameModel(
            old_name='Books',
            new_name='Watche',
        ),
    ]
